export const defaultConfig = {
  featureToggles: {
    checkoutScorePulse: true,
    checkoutBoardTargets: false,
    tvBoardZoom: false,
    styleCheckoutSuggestions: false,
    averageTrendArrow: false,
    turnStartSweep: false,
    tripleDoubleBullHits: false,
    cricketHighlighter: false,
    cricketGridFx: false,
    dartMarkerEmphasis: false,
    dartMarkerDarts: false,
    removeDartsNotification: false,
    singleBullSound: false,
    turnPointsCount: false,
    winnerFireworks: false,
    x01ScoreProgress: false,
    "themes.x01": false,
    "themes.shanghai": false,
    "themes.bermuda": false,
    "themes.cricket": false,
    "themes.bullOff": false,
  },
  features: {
    checkoutScorePulse: {
      enabled: true,
      effect: "scale",
      colorTheme: "159, 219, 88",
      intensity: "standard",
      triggerSource: "suggestion-first",
      debug: false,
    },
    checkoutBoardTargets: {
      enabled: false,
      effect: "pulse",
      singleRing: "both",
      colorTheme: "violet",
      outlineIntensity: "standard",
      debug: false,
    },
    tvBoardZoom: {
      enabled: false,
      zoomLevel: 2.75,
      zoomSpeed: "mittel",
      checkoutZoomEnabled: true,
      debug: false,
    },
    styleCheckoutSuggestions: {
      enabled: false,
      style: "ribbon",
      labelText: "CHECKOUT",
      colorTheme: "amber",
      debug: false,
    },
    averageTrendArrow: {
      enabled: false,
      durationMs: 320,
      size: "standard",
      debug: false,
    },
    turnStartSweep: {
      enabled: false,
      durationMs: 420,
      sweepStyle: "standard",
      debug: false,
    },
    tripleDoubleBullHits: {
      enabled: false,
      colorTheme: "kind-signal",
      animationStyle: "charge-release",
      debug: false,
    },
    cricketHighlighter: {
      enabled: false,
      showOpenObjectives: false,
      showDeadObjectives: true,
      irrelevantBoardDimStyle: "smoke",
      colorTheme: "standard",
      intensity: "normal",
      debug: false,
    },
    cricketGridFx: {
      enabled: false,
      rowWave: true,
      badgeBeacon: true,
      markProgress: true,
      pressureEdge: true,
      scoringStripe: true,
      deadRowMuted: true,
      deltaChips: true,
      hitSpark: true,
      roundTransitionWipe: true,
      pressureOverlay: true,
      colorTheme: "standard",
      intensity: "normal",
      debug: false,
    },
    dartMarkerEmphasis: {
      enabled: false,
      size: 6,
      color: "rgb(49, 130, 206)",
      effect: "glow",
      opacityPercent: 85,
      outline: "aus",
      debug: false,
    },
    dartMarkerDarts: {
      enabled: false,
      design: "autodarts",
      animateDarts: true,
      sizePercent: 100,
      hideOriginalMarkers: false,
      enableShadow: true,
      enableWobble: true,
      flightSpeed: "standard",
      debug: false,
    },
    removeDartsNotification: {
      enabled: false,
      imageSize: "standard",
      pulseAnimation: true,
      pulseScale: 1.04,
      debug: false,
    },
    singleBullSound: {
      enabled: false,
      volume: 0.9,
      cooldownMs: 700,
      pollIntervalMs: 0,
      debug: false,
    },
    turnPointsCount: {
      enabled: false,
      durationMs: 416,
      debug: false,
    },
    winnerFireworks: {
      enabled: false,
      style: "realistic",
      colorTheme: "autodarts",
      intensity: "standard",
      includeBullOut: true,
      pointerDismiss: true,
      debug: false,
    },
    x01ScoreProgress: {
      enabled: false,
      colorTheme: "checkout-focus",
      barSize: "standard",
      effect: "pulse-core",
      debug: false,
    },
    themes: {
      x01: {
        enabled: false,
        showAvg: true,
        backgroundDisplayMode: "fill",
        backgroundOpacity: 25,
        playerFieldTransparency: 10,
        backgroundImageDataUrl: "",
        debug: false,
      },
      shanghai: {
        enabled: false,
        showAvg: true,
        backgroundDisplayMode: "fill",
        backgroundOpacity: 25,
        playerFieldTransparency: 10,
        backgroundImageDataUrl: "",
        debug: false,
      },
      bermuda: {
        enabled: false,
        backgroundDisplayMode: "fill",
        backgroundOpacity: 25,
        playerFieldTransparency: 10,
        backgroundImageDataUrl: "",
        debug: false,
      },
      cricket: {
        enabled: false,
        showAvg: true,
        backgroundDisplayMode: "fill",
        backgroundOpacity: 25,
        playerFieldTransparency: 10,
        backgroundImageDataUrl: "",
        debug: false,
      },
      bullOff: {
        enabled: false,
        contrastPreset: "standard",
        backgroundDisplayMode: "fill",
        backgroundOpacity: 25,
        playerFieldTransparency: 10,
        backgroundImageDataUrl: "",
        debug: false,
      },
    },
  },
};
